platform:
  os: linux
  arch: arm
kind: pipeline
type: docker
name: default

steps:
- name: fetch
  image: drone/git
  commands:
  - git fetch --tags
  - git submodule init
  - git submodule update --recursive --remote

- name: Scrape brewfather and untappd infos
  image: golang:1.15
  environment:
    BREWFATHER_USERID:
      from_secret: brewfather_userid
    BREWFATHER_APIKEY:
      from_secret: brewfather_apikey
  commands:
  - mkdir -p data/batches
  - rm -f data/batches/*
  - cd bin
  - go run batches.go
  - go run scrape-untappd-images.go

- name: build pages including drafts
  image: plugins/hugo
  settings:
    # hugo_version: 0.78.2
    extended: true
    config: config.toml
    content: content
    buildDrafts: true
    url: https://preview.stackoverflow.beer
  when:
    branch:
      exclude:
      - main
      include:
      - draft/*

- name: Deploy to uberspace preview
  image: appleboy/drone-scp
  settings:
    host: tillk.uber.space
    username: tillk
    target: /var/www/virtual/tillk/preview.stackoverflow.beer/
    source: 
    - public/*
    strip_components: 1
    rm: true
    key:
      from_secret: uberspace_key
  when:
    branch:
      exclude:
      - main
      include:
      - draft/*

- name: build pages
  image: plugins/hugo
  settings:
    # hugo_version: 0.78.2
    extended: true
    config: config.toml
    content: content
  commands:
  - apk add libc6-compat libstdc++
  - /bin/drone-hugo
  when:
    branch: 
    - main

- name: Deploy to uberspace
  image: appleboy/drone-scp
  settings:
    host: tillk.uber.space
    username: tillk
    target: /var/www/virtual/tillk/stackoverflow.beer/
    source: 
    - public/*
    strip_components: 1
    rm: true
    key:
      from_secret: uberspace_key
  when:
    branch: 
    - main

trigger:
  event:
    exclude:
    - promote
    - cron
---
platform:
  os: linux
  arch: arm

kind: pipeline
type: docker
name: update-brewfather-infos

steps:
- name: Scrape brewfather and untappd infos
  image: golang:1.15
  environment:
    BREWFATHER_USERID:
      from_secret: brewfather_userid
    BREWFATHER_APIKEY:
      from_secret: brewfather_apikey
  commands:
  - mkdir -p data/batches
  - rm -f data/batches/*
  - cd bin
  - go run batches.go
  - go run scrape-untappd-images.go

- name: git add
  image: drone/git
  commands:
  - git add content/batches/*
  - git add data/batches/*

- name: push commit
  image: appleboy/drone-git-push
  settings:
    remote_name: origin
    branch: main
    local_ref: main

trigger:
  event:
  - cron
