platform:
  os: linux
  arch: arm
kind: pipeline
type: docker
name: default

steps:
- name: fetch
  image: drone/git
  commands:
  - git fetch --tags
  - git submodule update --recursive --remote

- name: build pages
  image: plugins/hugo
  settings:
    # hugo_version: 0.78.2
    extended: true
    config: config.toml
    content: content
  commands:
  - apk add libc6-compat libstdc++
  - /bin/drone-hugo

trigger:
  event:
    exclude:
    - promote

---
platform:
  os: linux
  arch: arm

kind: pipeline
type: docker
name: deploy-to-uberspace

steps:
- name: fetch
  image: drone/git
  commands:
  - git fetch --tags
  - git submodule update --recursive --remote

- name: Update batches
  image: golang:1.15
  environment:
    BREWFATHER_USERID:
      from_secret: brewfather_userid
    BREWFATHER_APIKEY:
      from_secret: brewfather_apikey
  commands:
  - mkdir -p data/batches && cd bin && go run batches.go

- name: build pages
  image: plugins/hugo
  settings:
    # hugo_version: 0.78.2
    extended: true
    config: config.toml
    content: content
  commands:
  - apk add libc6-compat libstdc++
  - /bin/drone-hugo

- name: Deploy to uberspace
  image: appleboy/drone-scp
  settings:
    host: tillk.uber.space
    username: tillk
    target: /var/www/virtual/tillk/stackoverflow.beer/
    source: 
    - public/*
    strip_components: 1
    rm: true
    key:
      from_secret: uberspace_key

trigger:
  event:
  - promote
  target:
  - production
