baseURL = "https://stackoverflow.beer/"
DefaultContentLanguage  = "en"
paginate                = 5
pluralizeListTitles     = false
title = "StackOverflow Brewery Dortmund"
theme = "hugo-future-imperfect-slim"
[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json"]
